spring:
   profiles:
    active: dev

---
spring:
  profiles: dev
  application:
  #服务名
    name: eureka-peer
server:
  port: 10000
 
eureka:
  instance:
     hostname: eureka1
  client:
     #检索服务
     fetch-registry: false
     # 是否注册自己
     register-with-eureka: false
     #改变 registered-replicas 和unavailable-replicas 的地址
     ##客户端默认去这个地址找注册中心
     service-url:
       defaultZone: http://localhost:10000,http://tomcat1:10000/eureka,http://tomcat2:10000/eureka,http://tomcat3:10000/eureka
  server:
    ##启动同步等待
    wait-time-in-ms-when-sync-empty: 0
    ##关闭自我保护
    enable-self-preservation: false
    ##数据更新间隔
    peer-eureka-nodes-update-interval-ms: 6000