server:
  port: 8881
spring:  application:    name: config-server
  cloud:    config:      server:
        native:
           search-locations: classpath:configs/
        encrypt:
          enabled: true
  security:
    user:
      name: sxc
      password: 123456
#eureka:
#  client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: ${eurekaUrl}
#     enable: true
#端点 以配置的方式 开关暴露的监控信息 actuator/health 访问
management:  endpoints:    web:      exposure:        include: "*"         