
server:
  port: 8881
spring:  application:    name: config-server
  cloud:    config:      server:
        native:
           search-locations: classpath:configs/
        encrypt:
          enabled: true
        overrides:
          eurekaUrl: http://localhost:10002/eureka
          eurekaServerPort: 10002
          eurekaClientPort: 20002   
          consumePort: 30001
          consumePort2: 30002
          monitorPort: 7777    
          zuulPort: 7001   
          zipkinUrl: http://eurekaMmonitor
          # adminUrl: http://admin
  security:
    user:
      name: sxc
      password: 123456
  rabbitmq:
    host: 192.168.239.135
    username: guest
    password: guest
    port: 5672                
#端点 以配置的方式 开关暴露的监控信息 actuator/health 访问
management:  endpoints:    web:      exposure:        include: "*"
  endpoint:
      health:
        show-details:    always
      shutdown:
        enabled: true  