server:
  port: 8888
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sxc9870/sbcloud.git
          force-pull: true
          search-paths: parent/configs
#端点 以配置的方式 开关暴露的监控信息 actuator/health 访问
management:
  endpoints:
    web:
      exposure:
        include: "*"
         