zuul:
  host:
    #链接超时时间
    connect-timeout-millis: 5000
    #socket超时时间
    socket-timeout-millis: 5000
    ##http连接池大小
    max-total-connections: 200
    ##每个host的最大连接数
    max-per-route-connections: 20
  ##前缀 通常不用  
  #prefix: /sxc
  ## 忽略服务  ignored-services:
  ##限流  ribbon-isolation-strategy: semaphore
  semaphore:    max-semaphores: 100
  
  
  ##转发
  routes:
    route1:
      ##拦截掉以sxc开头的请求
      path: /sxc/**
      #转发到百度
      url: http://www.baidu.com
    route2:
      path: /sxc1/**
      serviceId: consume
    sxcsxc:
      path: /login/zuulTest
      serviceId: consume
    needLoginPath:
      path: /**/**Auth
      serviceId: consume
      
sxc:
  zuul: 
    filters:
       needLoginRoutes: sxcsxc,needLoginPath
ribbon:
##    超过 ReadTimeout 会重试  
  ReadTimeout: 5000       
    ##超过 降级不重试
  ConnectTimeout: 5000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试   get默认会重试
           
hystrix:
    command:
        default:
            execution:
              timeout:
                enabled: true
              isolation:
                thread:  
                     ## 超过 timeoutInMilliseconds 不会重试
                   timeoutInMilliseconds: 6000    
