cloud: '123'
abc: 123
server:
  port: 30001
eureka:
  client:
     fetch-registry: true
     register-with-eureka: true
     service-url:
       defaultZone: ${eurekaUrl}


spring:
   
    zipkin:
    #  enabled: true
      base-url: ${zipkinUrl}
    sleuth:
      sampler:
         #2.0 是这个参数,1.0 是percentage
         probability: 1.0
    main:
      allow-bean-definition-overriding: true          

#打开以后fegin 超时才会降级
feign:
  hystrix:
    enabled: true
hystrix:
    command:
        default:
            execution:
              timeout:
                enabled: true
              isolation:
                thread:  
                     ## 超过 timeoutInMilliseconds 不会重试
                   timeoutInMilliseconds: 3000
ribbon:
##    超过 ReadTimeout 会重试  
  ReadTimeout: 1000       
    ##超过 降级不重试
  ConnectTimeout: 1000
  MaxAutoRetries: 0 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 0 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试   get默认会重试
       