cloud: '123'
abc: 123
server:
  port: 20002
eureka:
#  instance:
#     hostname: eurekaclient
  client:
     #检索服务
     fetch-registry: true
     # 是否注册自己
     register-with-eureka: true
     service-url:
       defaultZone: http://localhost:10001/eureka
     #enabled: true  
#testaaaa:
#  ribbon:
#     listOfServers:  eurekaclient