cloud: '123'
abc: 123
server:
  port: 10002
eureka:
   instance:
     leaseRenewalIntervalInSeconds: 10
     health-check-url-path: /actuator/health
   client:
     registryFetchIntervalSeconds: 5
     fetch-registry: true
     register-with-eureka: true
     service-url:
       defaultZone: ${eurekaUrl}
   server:
     ##启动同步等待
     wait-time-in-ms-when-sync-empty: 0
     ##关闭自我保护
     enable-self-preservation: false
     ##数据更新间隔
     peer-eureka-nodes-update-interval-ms: 6000
logging:
   file: "d://admin.log"
spring:
  #修改前綴
  boot: 
    admin:
       contextPath: /admin
    turbine : 
      clusters : default 
   
  security:
     basic: 
       enabled: false
     user:
        name: "user"
        password: "password"
zipkin: 
   ##关闭默认的映射使用自定义的
    ui: 
     enabled: false
turbine:
  aggregator:
    cluster-config: default
  app-config: CONSUME,ZUUL
  cluster-name-expression: new String("default")
management:
      metrics:
           web:
             server:
                auto-time-requests: false
                endpoint:
      health:
         show-details: ALWAYS
      endpoints:
         web:
           exposure:
              include: "*" 