cloud: '123'
abc: 123
server:
  port: 40001
eureka:
  client:
     fetch-registry: true
     register-with-eureka: true
     service-url:
       defaultZone: ${eurekaUrl}
#spring:
    #boot:
     #  admin:
       #   client:
       #     url: ${adminUrl}
management:
     metrics: 
         web: 
           server:
               auto-time-requests: false       