server:
  port: ${zuulPort}
eureka:
#  instance:
#     hostname: eurekaclient
  client:
     #检索服务
    # fetch-registry: true
     # 是否注册自己
    # register-with-eureka: true
     service-url:
       defaultZone: ${eurekaUrl}
