server:
  port: ${zuulPort}
eureka:
#  instance:
#     hostname: eurekaclient
  client:
     #检索服务
    # fetch-registry: true
     # 是否注册自己
    # register-with-eureka: true
     service-url:
       defaultZone: ${eurekaUrl}
       
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
    #boot:  admin挂在eureka上面就不需要单独配置
     #  admin:
     #     client:
      #      url: ${adminUrl}
    zipkin: 
      #enabled: true
      base-url: ${zipkinUrl}
    sleuth:
      sampler:
         probability: 1
  #    web:
  #       enabled: true
  #       skip-pattern: "/api-docs.*|/instances|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/trace|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream"